// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdd_ixFztHq1Og9dG9mm7zi6q1cezvGL0',
    appId: '1:334789091944:web:b140a2a27cd463b88cd1dd',
    messagingSenderId: '334789091944',
    projectId: 'bang9-28c52',
    authDomain: 'bang9-28c52.firebaseapp.com',
    storageBucket: 'bang9-28c52.firebasestorage.app',
    measurementId: 'G-VVDXTBSH2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8lLkTfKt3rH2ss0DaKT8hqvFnVE6ejYY',
    appId: '1:334789091944:android:b44213dc936af1898cd1dd',
    messagingSenderId: '334789091944',
    projectId: 'bang9-28c52',
    storageBucket: 'bang9-28c52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbhUqkpAItyVrSillV0ABeigPz_n0T_6s',
    appId: '1:334789091944:ios:a4dcfd47561761f58cd1dd',
    messagingSenderId: '334789091944',
    projectId: 'bang9-28c52',
    storageBucket: 'bang9-28c52.firebasestorage.app',
    iosBundleId: 'com.example.bang9Test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbhUqkpAItyVrSillV0ABeigPz_n0T_6s',
    appId: '1:334789091944:ios:a4dcfd47561761f58cd1dd',
    messagingSenderId: '334789091944',
    projectId: 'bang9-28c52',
    storageBucket: 'bang9-28c52.firebasestorage.app',
    iosBundleId: 'com.example.bang9Test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdd_ixFztHq1Og9dG9mm7zi6q1cezvGL0',
    appId: '1:334789091944:web:a1352599f4b428e38cd1dd',
    messagingSenderId: '334789091944',
    projectId: 'bang9-28c52',
    authDomain: 'bang9-28c52.firebaseapp.com',
    storageBucket: 'bang9-28c52.firebasestorage.app',
    measurementId: 'G-ETVH9L0HX7',
  );
}
